"""bepress / Digital Commons platform (Elsevier's institutional repository stack).

Hosts a huge fraction of US institutional repositories — any URL like
`https://digitalcommons.<institution>.edu/<journal>/` or
`https://scholar.<institution>.edu/<journal>/` is overwhelmingly likely
to be bepress. Detection is multi-pronged:

  - URL host matches `digitalcommons.*.edu` or `scholarship.*.edu` /
    `scholarworks.*.edu` etc.
  - HTML body contains `<meta name="bepress_citation_*">` tags (every
    article page emits these, and many archive pages do too).
  - "powered by bepress" / "Digital Commons" footer text.

URL conventions:
  - Archive listing: <base>/<journal>/all_issues.html (lists every vol/iss)
  - Issue page:      <base>/<journal>/vol<N>/iss<M>/
  - Article page:    <base>/<journal>/vol<N>/iss<M>/<art_num>/
  - PDF download:    <base>/cgi/viewcontent.cgi?article=<id>&context=<journal>
                     OR a direct .pdf URL listed in `bepress_citation_pdf_url`
                     meta tag on the article page.

The generated downloader walks all_issues.html, follows each issue
link, scrapes article PDF URLs from the `bepress_citation_pdf_url`
meta tag on each article page, and downloads to pdfs/vol<N>iss<M>/.
"""
from __future__ import annotations

import re
from pathlib import Path
from urllib.parse import urlparse

from .base import Platform, _basic_slug


_BEPRESS_HOST = re.compile(
    r"^(digitalcommons|scholarworks|scholarship|scholar|repository|commons|"
    r"openscholarship|ir|works|via|trace|engagedscholarship|scholarcommons)"
    r"\.[a-z0-9-]+\.(edu|org)$",
    re.IGNORECASE,
)


def _detect(url: str, html: str) -> bool:
    host = urlparse(url).netloc.lower()
    if _BEPRESS_HOST.match(host):
        return True
    if html:
        if 'name="bepress_citation_' in html:
            return True
        if "Powered by" in html and "bepress" in html.lower():
            return True
        if "Digital Commons" in html and "bepress" in html.lower():
            return True
    return False


_JOURNAL_FROM_URL = re.compile(
    r"^https?://[^/]+/([a-z0-9_-]+)(?:/|$)", re.IGNORECASE,
)


def _default_slug(url: str) -> tuple[str, str, str]:
    m = _JOURNAL_FROM_URL.match(url)
    if m and m.group(1).lower() not in ("cgi", "do", "vol", "static"):
        slug = m.group(1).lower()
        name_guess = slug.replace("-", " ").replace("_", " ").title()
        return (name_guess, slug, f"{slug}-issue")
    return ("New Journal", "newjournal", "newjournal-issue")


_JOURNAL_PY = '''"""
Journal-specific config for {name} (bepress / Digital Commons).

Generated by the New Journal wizard. PDFs land in pdfs/vol<N>iss<M>/
to match Digital Commons' volume/issue convention.
"""

from __future__ import annotations

import re


JOURNAL_NAME = "{name}"
JOURNAL_SLUG = "{slug}"
BATCH_ID_PREFIX = "{batch_prefix}"

# bepress issue subdirs are vol<N>iss<M>; override the default `volume(\\d+)` parser.
VOLUME_DIR_PATTERN = re.compile(r"^vol(\\d+)iss(\\d+)$", re.IGNORECASE)


EXTRACTION_CONFIG = {{
    "use_doi_annotation_extraction": True,
    "use_low_text_ocr":              True,
    "use_scramble_detection":        True,
    "use_page_break_recovery":       True,
    "use_mla_tei_fallback":          True,
    "use_mla_raw_text_fallback":     True,
    "use_anystyle_fallback":         True,
    "use_per_citation_parse":        True,
    "use_em_dash_patcher":           True,
    "force_ocr_volumes":             {force_ocr_volumes},
    "min_text_chars_for_skip_ocr":   3000,
    "scramble_ratio_threshold":      1.5,
    "anystyle_container":            "anystyle",
    "anystyle_http_url":             "http://localhost:4567",
}}


ENRICHMENT_CONFIG = {{
    "crossref":         True,
    "openalex":         False,
    "semantic_scholar": False,
    "rate_limit_s":     0.1,
}}
'''


_DOWNLOADER_PY = '''"""
{name} downloader (bepress / Digital Commons).

Walks <base>/<journal>/all_issues.html, follows every issue link, parses
each article page for `bepress_citation_pdf_url`, and downloads the PDF.

Issue subdirs land at pdfs/vol<N>iss<M>/, matching Digital Commons'
volume/issue convention.

Usage:
    python downloader.py                          # entire archive
    python downloader.py --issues vol3iss1 vol3iss2
"""

from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup


BASE_URL = "{base_url}"
JOURNAL_PATH = "{journal_path}"
ALL_ISSUES_URL = f"{{BASE_URL}}{{JOURNAL_PATH}}all_issues.html"
USER_AGENT = "{slug}-reference-scraper/1.0 (+local research tool)"
DOWNLOAD_DELAY_S = 0.5


_ISSUE_PATH = re.compile(r"/vol(\\d+)/iss(\\d+)/?$", re.IGNORECASE)


def discover_issues(session: requests.Session) -> list[dict]:
    r = session.get(ALL_ISSUES_URL, timeout=30)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    seen: set[tuple[int, int]] = set()
    out: list[dict] = []
    for a in soup.find_all("a", href=True):
        href = urljoin(ALL_ISSUES_URL, a["href"])
        m = _ISSUE_PATH.search(urlparse(href).path)
        if not m:
            continue
        vol, iss = int(m.group(1)), int(m.group(2))
        if (vol, iss) in seen:
            continue
        seen.add((vol, iss))
        out.append({{
            "vol": vol, "iss": iss,
            "slug": f"vol{{vol}}iss{{iss}}",
            "url": href,
        }})
    out.sort(key=lambda x: (x["vol"], x["iss"]))
    return out


def issue_article_urls(issue: dict, session: requests.Session) -> list[str]:
    r = session.get(issue["url"], timeout=30)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    out: list[str] = []
    for a in soup.find_all("a", href=True):
        href = urljoin(issue["url"], a["href"])
        path = urlparse(href).path.rstrip("/")
        # Article URLs end in /<n> after /vol<N>/iss<M>/
        if _ISSUE_PATH.search(path):
            continue  # skip the issue page itself
        if re.search(r"/vol\\d+/iss\\d+/\\d+$", path):
            out.append(href)
    return sorted(set(out))


def article_pdf_url(article_url: str, session: requests.Session) -> str | None:
    r = session.get(article_url, timeout=30)
    if r.status_code != 200:
        return None
    soup = BeautifulSoup(r.text, "html.parser")
    meta = soup.find("meta", attrs={{"name": "bepress_citation_pdf_url"}})
    if meta and meta.get("content"):
        return meta["content"]
    # Fallback: any <a> link to a .pdf
    for a in soup.find_all("a", href=True):
        if a["href"].lower().endswith(".pdf"):
            return urljoin(article_url, a["href"])
    return None


def download_issue(issue: dict, out_root: Path, session: requests.Session) -> int:
    issue_dir = out_root / issue["slug"]
    issue_dir.mkdir(parents=True, exist_ok=True)
    arts = issue_article_urls(issue, session)
    print(f"[{{issue['slug']}}] {{len(arts)}} article(s)", flush=True)
    written = 0
    for art_url in arts:
        pdf_url = article_pdf_url(art_url, session)
        if not pdf_url:
            print(f"  !! no PDF link on {{art_url}}", flush=True)
            continue
        # Filename = article-id (last numeric segment of the article page URL)
        m = re.search(r"/(\\d+)/?$", urlparse(art_url).path)
        if not m:
            continue
        target = issue_dir / f"{{m.group(1)}}.pdf"
        if target.exists() and target.stat().st_size > 0:
            continue
        try:
            r = session.get(pdf_url, timeout=120)
            r.raise_for_status()
            target.write_bytes(r.content)
            written += 1
            print(f"  ↓ {{target.name}} ({{target.stat().st_size//1024}} KB)", flush=True)
            time.sleep(DOWNLOAD_DELAY_S)
        except Exception as e:
            print(f"  !! {{target.name}}: {{e}}", flush=True)
    return written


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--issues", nargs="*",
                   help="Specific issue slugs (e.g. vol3iss1). Default: all.")
    p.add_argument("--output", default="pdfs")
    args = p.parse_args()
    out_root = Path(args.output).resolve()

    session = requests.Session()
    session.headers["User-Agent"] = USER_AGENT

    print(f"=== discovering issues at {{ALL_ISSUES_URL}}", flush=True)
    issues = discover_issues(session)
    if args.issues:
        issues = [i for i in issues if i["slug"] in args.issues]
    print(f"=== {{len(issues)}} issue(s) to process", flush=True)

    total = 0
    for issue in issues:
        total += download_issue(issue, out_root, session)
    print(f"=== done: {{total}} new PDFs", flush=True)


if __name__ == "__main__":
    main()
'''


_SCRAPER_PY = '''"""
{name} reference scraper.

Thin wrapper around `_shared.cli.run`.
"""

from __future__ import annotations

import sys
from pathlib import Path


_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
for _p in (str(_PROJECT_ROOT), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from _shared.cli import run  # noqa: E402
import journal  # noqa: E402


if __name__ == "__main__":
    sys.exit(run(journal))
'''


def _scaffold(journal_dir: Path, ctx: dict) -> None:
    name = ctx["name"]
    slug = ctx.get("slug") or _basic_slug(name)
    batch_prefix = ctx.get("batch_prefix") or f"{slug}-issue"
    archive_url = ctx.get("archive_url", "").rstrip("/")

    # Extract base + journal path from the archive URL
    parsed = urlparse(archive_url) if archive_url else None
    base_url = f"{parsed.scheme}://{parsed.netloc}" if parsed and parsed.scheme else "https://example.org"
    path = parsed.path if parsed else "/"
    # Trim trailing all_issues.html or pages so journal_path ends with /
    path = re.sub(r"/all_issues\.html$", "/", path, flags=re.IGNORECASE)
    if not path.endswith("/"):
        path += "/"
    journal_path = path or f"/{slug}/"

    force_ocr_volumes = ctx.get("force_ocr_volumes") or []

    journal_dir.mkdir(parents=True, exist_ok=True)
    (journal_dir / "journal.py").write_text(
        _JOURNAL_PY.format(
            name=name, slug=slug, batch_prefix=batch_prefix,
            force_ocr_volumes=repr(list(force_ocr_volumes)),
        ),
        encoding="utf-8",
    )
    (journal_dir / "downloader.py").write_text(
        _DOWNLOADER_PY.format(
            name=name, slug=slug,
            base_url=base_url, journal_path=journal_path,
        ),
        encoding="utf-8",
    )
    (journal_dir / "scraper.py").write_text(
        _SCRAPER_PY.format(name=name),
        encoding="utf-8",
    )

    import json
    (journal_dir / "depositor.json").write_text(
        json.dumps({
            "depositor_name": ctx.get("depositor_name", ""),
            "email_address": ctx.get("depositor_email", ""),
        }, indent=2),
        encoding="utf-8",
    )

    # Copy ATD's enricher.py as a starter (it's CrossRef-only and works
    # for any journal type)
    src = journal_dir.parent / "Across the Disciplines" / "Structured Scraper" / "enricher.py"
    dest_dir = journal_dir / "Structured Scraper"
    dest_dir.mkdir(parents=True, exist_ok=True)
    if src.exists():
        (dest_dir / "enricher.py").write_bytes(src.read_bytes())
        req = src.parent / "requirements.txt"
        if req.exists():
            (dest_dir / "requirements.txt").write_bytes(req.read_bytes())


PLATFORM = Platform(
    key="bepress",
    label="bepress / Digital Commons",
    detect=_detect,
    default_slug=_default_slug,
    scaffold=_scaffold,
    notes=[
        "bepress journals use vol<N>iss<M> subdirs (e.g. pdfs/vol3iss1/), "
        "not WAC-style volumeN. The generated journal.py overrides "
        "VOLUME_DIR_PATTERN to match.",
        "The downloader scrapes <archive>/all_issues.html for issue links, "
        "then each article page for the `bepress_citation_pdf_url` meta tag. "
        "Both signals are stable across the bepress platform.",
        "Many bepress sites front a single PDF download URL that requires "
        "session cookies (`cgi/viewcontent.cgi`). The downloader uses a "
        "persistent requests.Session so this usually just works.",
    ],
)
