"""Janeway platform (open-source journal management system).

Janeway is Birkbeck / Open Library of Humanities' Django-based
alternative to OJS. Used by many OA humanities journals (Open Library
of Humanities titles, Modernist Cultures, Glossa-ish journals, etc.).

Detection signals:
  - HTML meta tag: <meta name="generator" content="Janeway ..." />
  - Footer text "powered by Janeway" or "Janeway Platform"
  - URL patterns specific to Janeway:
       /articles/                  → list of articles
       /article/id/<n>/            → article landing
       /article/<n>/galley/<gid>/download/
       /issues/                    → issue archive

URL conventions:
  - Issue archive: <base>/issues/
  - Issue page:    <base>/issue/<id>/
  - Article page:  <base>/article/id/<id>/
  - PDF download:  <base>/article/id/<id>/galley/<gid>/download/
  - DOIs are usually displayed prominently on the article page in the
    <meta name="citation_doi"> tag.
"""
from __future__ import annotations

import re
from pathlib import Path
from urllib.parse import urlparse

from .base import Platform, _basic_slug


_JANEWAY_PATH = re.compile(
    r"/(articles?|issues?|site)/(?:id/)?\d*/?$", re.IGNORECASE,
)


def _detect(url: str, html: str) -> bool:
    # Strongest signals: explicit branding (kept by community-edition deploys)
    if html:
        if re.search(r'<meta\s+name=["\']generator["\']\s+content=["\'][^"\']*Janeway',
                     html, re.IGNORECASE):
            return True
        if "powered by" in html.lower() and "janeway" in html.lower():
            return True
        if "Janeway Platform" in html:
            return True
        # URL-pattern detection for production deploys that have stripped
        # Janeway branding (e.g. OLH titles, Glossa, Modernist Cultures).
        # The /article/id/<n>/ form — with the literal "/id/" segment
        # between "article" and the numeric ID — is essentially unique
        # to Janeway. OJS uses /article/view/<n>, bepress uses
        # /<journal>/vol<N>/iss<M>/<art>/, WAC uses /docs/<journal>/...
        if re.search(r"/article/id/\d+/?", html):
            return True
        # Secondary URL fingerprints used by stripped-branding deploys.
        # Janeway distinctively uses /site/<name>/ for static pages
        # (about, contact, etc.) and /issue/<n>/ for issue landings.
        # OJS uses /about/, /issue/view/<n>; bepress uses /pages/<name>;
        # WAC has no equivalent. So /site/<name> + /issue/<n> together
        # is essentially a Janeway-only combination.
        has_issue_path = bool(re.search(r"/issue/\d+/?", html))
        has_site_path = bool(re.search(r"/site/[a-z][a-z0-9-]*/?", html))
        has_articles_path = "/articles/" in html
        if has_issue_path and (has_site_path or has_articles_path):
            return True
    return False


def _default_slug(url: str) -> tuple[str, str, str]:
    # Janeway journals usually have a host like <journal>.<publisher>.com,
    # so the subdomain is the best slug guess
    host = urlparse(url).netloc
    if "." in host:
        parts = host.split(".")
        if parts[0] not in ("www", ""):
            slug = parts[0].lower()
            name_guess = parts[0].replace("-", " ").title()
            return (name_guess, slug, f"{slug}-issue")
    return ("New Journal", "newjournal", "newjournal-issue")


_JOURNAL_PY = '''"""
Journal-specific config for {name} (Janeway-hosted).

Generated by the New Journal wizard. Janeway issues land in
pdfs/issue<N>/ to mirror Janeway's flat issue-ID convention.
"""

from __future__ import annotations

import re


BASE_URL = "{base_url}"

ARCHIVE_INDEX_URL = f"{{BASE_URL}}/issues/"
ISSUE_URL_TEMPLATE = f"{{BASE_URL}}/issue/{{{{issue_id}}}}/"
ARTICLE_URL_TEMPLATE = f"{{BASE_URL}}/article/id/{{{{article_id}}}}/"
GALLEY_DOWNLOAD_TEMPLATE = (
    f"{{BASE_URL}}/article/id/{{{{article_id}}}}/galley/{{{{galley_id}}}}/download/"
)

USER_AGENT = "{slug}-reference-scraper/1.0 (+local research tool)"


JOURNAL_NAME = "{name}"
JOURNAL_SLUG = "{slug}"
BATCH_ID_PREFIX = "{batch_prefix}"

# Janeway issue subdirs are issue<id> (flat numeric ID, not vol/iss).
VOLUME_DIR_PATTERN = re.compile(r"^issue(\\d+)$", re.IGNORECASE)


EXTRACTION_CONFIG = {{
    "use_doi_annotation_extraction": True,
    "use_low_text_ocr":              True,
    "use_scramble_detection":        True,
    "use_page_break_recovery":       True,
    "use_mla_tei_fallback":          True,
    "use_mla_raw_text_fallback":     True,
    "use_anystyle_fallback":         True,
    "use_per_citation_parse":        True,
    "use_em_dash_patcher":           True,
    "force_ocr_volumes":             [],
    "min_text_chars_for_skip_ocr":   3000,
    "scramble_ratio_threshold":      1.5,
    "anystyle_container":            "anystyle",
    "anystyle_http_url":             "http://localhost:4567",
}}


ENRICHMENT_CONFIG = {{
    "crossref":         True,
    "openalex":         False,
    "semantic_scholar": False,
    "rate_limit_s":     0.1,
}}
'''


_DOWNLOADER_PY = '''"""
{name} downloader (Janeway).

Walks <base>/issues/ for issue links, then each issue page for article
links, and downloads each article's PDF galley.

Saves to pdfs/issue<id>/<article_id>.pdf — and the HTML galley to
html/issue<id>/<article_id>.html when one is available.

Usage:
    python downloader.py                          # entire archive
    python downloader.py --issues issue42 issue43
"""

from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
import journal


DOWNLOAD_DELAY_S = 0.5

_ISSUE_PATH = re.compile(r"/issue/(\\d+)/?$", re.IGNORECASE)
_ARTICLE_PATH = re.compile(r"/article/id/(\\d+)/?$", re.IGNORECASE)


def discover_issues(session: requests.Session) -> list[dict]:
    r = session.get(journal.ARCHIVE_INDEX_URL, timeout=30)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    out: dict[int, dict] = {{}}
    for a in soup.find_all("a", href=True):
        href = urljoin(journal.ARCHIVE_INDEX_URL, a["href"])
        m = _ISSUE_PATH.search(urlparse(href).path)
        if not m:
            continue
        iid = int(m.group(1))
        if iid not in out:
            out[iid] = {{
                "issue_id": iid,
                "slug": f"issue{{iid}}",
                "url": href,
                "label": a.get_text(strip=True),
            }}
    return sorted(out.values(), key=lambda x: x["issue_id"])


def discover_articles(issue: dict, session: requests.Session) -> list[int]:
    r = session.get(issue["url"], timeout=30)
    r.raise_for_status()
    seen: set[int] = set()
    out: list[int] = []
    for m in _ARTICLE_PATH.finditer(r.text):
        aid = int(m.group(1))
        if aid in seen:
            continue
        seen.add(aid)
        out.append(aid)
    return out


def article_galleys(article_url: str,
                    session: requests.Session) -> list[tuple[str, int]]:
    """Return [(kind, galley_id), ...] for the article. Kind is 'pdf' or
    'html'."""
    r = session.get(article_url, timeout=30)
    if r.status_code != 200:
        return []
    soup = BeautifulSoup(r.text, "html.parser")
    out: list[tuple[str, int]] = []
    # Galley download links: /article/id/<aid>/galley/<gid>/download/
    for a in soup.find_all("a", href=True):
        m = re.search(r"/article/(?:id/)?\\d+/galley/(\\d+)/download/?",
                      a["href"], re.IGNORECASE)
        if not m:
            continue
        text = a.get_text(strip=True).lower()
        kind = "pdf"
        if "html" in text or "xml" in text:
            kind = "html"
        out.append((kind, int(m.group(1))))
    return out


def download_article(issue: dict, article_id: int,
                     pdfs_root: Path, html_root: Path,
                     session: requests.Session) -> None:
    art_url = journal.ARTICLE_URL_TEMPLATE.format(article_id=article_id)
    galleys = article_galleys(art_url, session)

    pdf_dir = pdfs_root / issue["slug"]
    html_dir = html_root / issue["slug"]
    pdf_dir.mkdir(parents=True, exist_ok=True)

    for kind, gid in galleys:
        url = journal.GALLEY_DOWNLOAD_TEMPLATE.format(
            article_id=article_id, galley_id=gid,
        )
        if kind == "pdf":
            target = pdf_dir / f"{{article_id}}.pdf"
        else:
            html_dir.mkdir(parents=True, exist_ok=True)
            target = html_dir / f"{{article_id}}.html"
        if target.exists() and target.stat().st_size > 0:
            continue
        try:
            r = session.get(url, timeout=120)
            r.raise_for_status()
            target.write_bytes(r.content)
            print(f"  ↓ {{issue['slug']}}/{{target.name}}", flush=True)
            time.sleep(DOWNLOAD_DELAY_S)
        except Exception as e:
            print(f"  !! {{issue['slug']}}/{{target.name}}: {{e}}", flush=True)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--issues", nargs="*",
                   help="Specific issue slugs (e.g. issue42). Default: all.")
    args = p.parse_args()

    session = requests.Session()
    session.headers["User-Agent"] = journal.USER_AGENT

    pdfs_root = _HERE / "pdfs"
    html_root = _HERE / "html"

    print(f"=== discovering issues at {{journal.ARCHIVE_INDEX_URL}}", flush=True)
    issues = discover_issues(session)
    if args.issues:
        issues = [i for i in issues if i["slug"] in args.issues]
    print(f"=== {{len(issues)}} issue(s) to process", flush=True)

    for issue in issues:
        print(f"[{{issue['slug']}}] {{issue.get('label', '')}}", flush=True)
        try:
            ids = discover_articles(issue, session)
        except Exception as e:
            print(f"  !! issue page failed: {{e}}", flush=True)
            continue
        print(f"  {{len(ids)}} article(s)", flush=True)
        for aid in ids:
            download_article(issue, aid, pdfs_root, html_root, session)


if __name__ == "__main__":
    main()
'''


_SCRAPER_PY = '''"""
{name} reference scraper.

Thin wrapper around `_shared.cli.run`.
"""

from __future__ import annotations

import sys
from pathlib import Path


_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
for _p in (str(_PROJECT_ROOT), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from _shared.cli import run  # noqa: E402
import journal  # noqa: E402


if __name__ == "__main__":
    sys.exit(run(journal))
'''


def _scaffold(journal_dir: Path, ctx: dict) -> None:
    name = ctx["name"]
    slug = ctx.get("slug") or _basic_slug(name)
    batch_prefix = ctx.get("batch_prefix") or f"{slug}-issue"

    archive_url = ctx.get("archive_url", "").rstrip("/")
    parsed = urlparse(archive_url) if archive_url else None
    base_url = (
        f"{parsed.scheme}://{parsed.netloc}"
        if parsed and parsed.scheme else "https://example.org"
    )

    journal_dir.mkdir(parents=True, exist_ok=True)
    (journal_dir / "journal.py").write_text(
        _JOURNAL_PY.format(
            name=name, slug=slug, batch_prefix=batch_prefix,
            base_url=base_url,
        ),
        encoding="utf-8",
    )
    (journal_dir / "downloader.py").write_text(
        _DOWNLOADER_PY.format(name=name, slug=slug),
        encoding="utf-8",
    )
    (journal_dir / "scraper.py").write_text(
        _SCRAPER_PY.format(name=name),
        encoding="utf-8",
    )

    import json
    (journal_dir / "depositor.json").write_text(
        json.dumps({
            "depositor_name": ctx.get("depositor_name", ""),
            "email_address": ctx.get("depositor_email", ""),
        }, indent=2),
        encoding="utf-8",
    )

    # Janeway journals often have HTML galleys; prefer copying Prompt's
    # enricher (also HTML-aware). Fall back to ATD's.
    src_options = [
        journal_dir.parent / "Prompt" / "Structured Scraper" / "enricher.py",
        journal_dir.parent / "Across the Disciplines" / "Structured Scraper" / "enricher.py",
    ]
    dest_dir = journal_dir / "Structured Scraper"
    dest_dir.mkdir(parents=True, exist_ok=True)
    for src in src_options:
        if src.exists():
            (dest_dir / "enricher.py").write_bytes(src.read_bytes())
            req = src.parent / "requirements.txt"
            if req.exists():
                (dest_dir / "requirements.txt").write_bytes(req.read_bytes())
            break


PLATFORM = Platform(
    key="janeway",
    label="Janeway (Birkbeck / Open Library of Humanities)",
    detect=_detect,
    default_slug=_default_slug,
    scaffold=_scaffold,
    notes=[
        "Janeway issue subdirs are issue<id> (flat numeric, e.g. issue42), "
        "not vol/iss. The generated journal.py overrides VOLUME_DIR_PATTERN.",
        "Janeway articles usually expose both PDF and HTML galleys; the "
        "downloader saves both and the scraper prefers HTML when present.",
        "Detection relies on the Janeway generator meta tag or footer text; "
        "URL-only detection is intentionally weak to avoid false positives "
        "against custom CMS sites that happen to have /article/ paths.",
    ],
)
