"""Open Journal Systems platform (3.x).

OJS is the open-source journal management system used by hundreds of
small-press humanities journals. Detection: HTML meta tag
`<meta name="generator" content="Open Journal Systems...">` or URL
pattern `/index.php/<journal>/issue/`.

Article URLs:
    /index.php/<journal>/issue/archive
    /index.php/<journal>/issue/view/<id>
    /index.php/<journal>/article/view/<id>
    /index.php/<journal>/article/download/<id>/<galley_id>

OJS journals often expose both PDF and HTML galleys for each article.
The HTML galley is usually richer (inline DOIs, structured reference
list), so the downloader saves both and the scraper prefers HTML when
it's available.
"""
from __future__ import annotations

import re
from pathlib import Path
from urllib.parse import urlparse

from .base import Platform, _basic_slug


_OJS_PATH = re.compile(r"/index\.php/([a-z0-9_-]+)/", re.IGNORECASE)


def _detect(url: str, html: str) -> bool:
    if _OJS_PATH.search(url):
        return True
    if html:
        if "Open Journal Systems" in html:
            return True
        if 'name="generator"' in html and "OJS" in html:
            return True
    return False


def _default_slug(url: str) -> tuple[str, str, str]:
    m = _OJS_PATH.search(url)
    slug = m.group(1).lower() if m else "newjournal"
    name_guess = slug.replace("-", " ").replace("_", " ").title()
    return (name_guess, slug, f"{slug}-issue")


_JOURNAL_PY = '''"""
Journal-specific config for {name} (OJS-hosted).

Generated by the New Journal wizard. The HTML galley path is preferred
over PDF when both exist for the same article.
"""

from __future__ import annotations

import re


BASE_URL = "{base_url}"
OJS_PREFIX = "{ojs_prefix}"

ARCHIVE_INDEX_URL = f"{{BASE_URL}}{{OJS_PREFIX}}/issue/archive"
ISSUE_URL_TEMPLATE = f"{{BASE_URL}}{{OJS_PREFIX}}/issue/view/{{{{ojs_id}}}}"
ARTICLE_URL_TEMPLATE = f"{{BASE_URL}}{{OJS_PREFIX}}/article/view/{{{{article_id}}}}"
GALLEY_DOWNLOAD_TEMPLATE = (
    f"{{BASE_URL}}{{OJS_PREFIX}}/article/download/"
    "{{{{article_id}}}}/{{{{galley_id}}}}?inline=1"
)

# DOI pattern — adjust this once you confirm the journal's DOI stem.
DOI_PATTERN = re.compile(r"{doi_pattern}")

USER_AGENT = "{slug}-reference-scraper/1.0 (+local research tool)"


JOURNAL_NAME = "{name}"
JOURNAL_SLUG = "{slug}"
BATCH_ID_PREFIX = "{batch_prefix}"

# OJS issues are stored as v<N>i<M> on disk; override the default
# `volume(\\d+)` parser accordingly.
VOLUME_DIR_PATTERN = re.compile(r"^v(\\d+)i\\d+$", re.IGNORECASE)


EXTRACTION_CONFIG = {{
    "use_doi_annotation_extraction": True,
    "use_low_text_ocr":              True,
    "use_scramble_detection":        True,
    "use_page_break_recovery":       True,
    "use_mla_tei_fallback":          True,
    "use_mla_raw_text_fallback":     True,
    "use_anystyle_fallback":         True,
    "use_per_citation_parse":        True,
    "use_em_dash_patcher":           True,
    "force_ocr_volumes":             [],
    "min_text_chars_for_skip_ocr":   3000,
    "scramble_ratio_threshold":      1.5,
    "anystyle_container":            "anystyle",
    "anystyle_http_url":             "http://localhost:4567",
}}


ENRICHMENT_CONFIG = {{
    "crossref":         True,
    "openalex":         False,
    "semantic_scholar": False,
    "rate_limit_s":     0.1,
}}
'''


_DOWNLOADER_PY = '''"""
{name} OJS downloader.

Walks the OJS archive index, enumerates issues and articles, and
downloads each article's HTML and PDF galleys to parallel trees:
    html/<v<N>i<M>>/<article_id>.html
    pdfs/<v<N>i<M>>/<article_id>.pdf

Usage:
    python downloader.py                 # entire archive
    python downloader.py --issues v9i2 v9i1
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path

import requests
from bs4 import BeautifulSoup

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
import journal


DOWNLOAD_DELAY_S = 0.5

_VOL_NUM_LABEL = re.compile(r"Vol\\.\\s*(\\d+)\\s*No\\.\\s*(\\d+)", re.IGNORECASE)
_ISSUE_PATH = re.compile(r"/issue/view/(\\d+)")
_ARTICLE_PATH = re.compile(r"/article/view/(\\d+)(?![\\d/])")


def discover_issues(session: requests.Session) -> list[dict]:
    r = session.get(journal.ARCHIVE_INDEX_URL, timeout=30)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    issues: dict[int, dict] = {{}}
    for a in soup.find_all("a", href=True):
        m = _ISSUE_PATH.search(a["href"])
        if not m:
            continue
        ojs_id = int(m.group(1))
        label = a.get_text(strip=True) or ""
        if ojs_id not in issues:
            issues[ojs_id] = {{"ojs_id": ojs_id, "label": label}}
    out = []
    for ojs_id, meta in issues.items():
        vm = _VOL_NUM_LABEL.search(meta["label"])
        if vm:
            slug = f"v{{vm.group(1)}}i{{vm.group(2)}}"
        else:
            slug = f"issue-{{ojs_id}}"
        meta["slug"] = slug
        out.append(meta)
    out.sort(key=lambda x: x["ojs_id"])
    return out


def discover_articles(issue: dict, session: requests.Session) -> list[int]:
    url = journal.ISSUE_URL_TEMPLATE.format(ojs_id=issue["ojs_id"])
    r = session.get(url, timeout=30)
    r.raise_for_status()
    ids: list[int] = []
    seen = set()
    for m in _ARTICLE_PATH.finditer(r.text):
        aid = int(m.group(1))
        if aid in seen:
            continue
        seen.add(aid)
        ids.append(aid)
    return ids


def download_article(issue: dict, article_id: int,
                     pdfs_root: Path, html_root: Path,
                     session: requests.Session) -> None:
    art_url = journal.ARTICLE_URL_TEMPLATE.format(article_id=article_id)
    r = session.get(art_url, timeout=30)
    if r.status_code != 200:
        return
    soup = BeautifulSoup(r.text, "html.parser")
    galleys: list[tuple[str, int]] = []  # (kind, galley_id)
    for a in soup.select("a.obj_galley_link"):
        href = a.get("href", "")
        gm = re.search(r"/article/view/\\d+/(\\d+)", href)
        if not gm:
            continue
        kind = "html" if "html" in a.get_text(strip=True).lower() else "pdf"
        galleys.append((kind, int(gm.group(1))))

    issue_slug = issue["slug"]
    html_dir = html_root / issue_slug
    pdf_dir = pdfs_root / issue_slug
    html_dir.mkdir(parents=True, exist_ok=True)
    pdf_dir.mkdir(parents=True, exist_ok=True)

    for kind, gid in galleys:
        url = journal.GALLEY_DOWNLOAD_TEMPLATE.format(
            article_id=article_id, galley_id=gid,
        )
        ext = "html" if kind == "html" else "pdf"
        target = (html_dir if kind == "html" else pdf_dir) / f"{{article_id}}.{{ext}}"
        if target.exists() and target.stat().st_size > 0:
            continue
        try:
            r = session.get(url, timeout=120)
            r.raise_for_status()
            target.write_bytes(r.content)
            print(f"  ↓ {{issue_slug}}/{{article_id}}.{{ext}}", flush=True)
            time.sleep(DOWNLOAD_DELAY_S)
        except Exception as e:
            print(f"  !! {{issue_slug}}/{{article_id}}.{{ext}}: {{e}}", flush=True)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--issues", nargs="*",
                   help="Specific issue slugs (e.g. v9i2). Default: all.")
    args = p.parse_args()

    session = requests.Session()
    session.headers["User-Agent"] = journal.USER_AGENT

    pdfs_root = _HERE / "pdfs"
    html_root = _HERE / "html"

    print(f"=== discovering issues at {{journal.ARCHIVE_INDEX_URL}}", flush=True)
    issues = discover_issues(session)
    if args.issues:
        issues = [i for i in issues if i["slug"] in args.issues]
    print(f"=== {{len(issues)}} issue(s) to process", flush=True)

    for issue in issues:
        print(f"[{{issue['slug']}}] {{issue.get('label', '')}}", flush=True)
        try:
            article_ids = discover_articles(issue, session)
        except Exception as e:
            print(f"  !! issue page failed: {{e}}", flush=True)
            continue
        print(f"  {{len(article_ids)}} article(s)", flush=True)
        for aid in article_ids:
            download_article(issue, aid, pdfs_root, html_root, session)


if __name__ == "__main__":
    main()
'''


_SCRAPER_PY = '''"""
{name} reference scraper.

Thin wrapper around `_shared.cli.run`. Per-journal config in journal.py.
"""

from __future__ import annotations

import sys
from pathlib import Path


_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
for _p in (str(_PROJECT_ROOT), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from _shared.cli import run  # noqa: E402
import journal  # noqa: E402


if __name__ == "__main__":
    sys.exit(run(journal))
'''


def _scaffold(journal_dir: Path, ctx: dict) -> None:
    name = ctx["name"]
    slug = ctx.get("slug") or _basic_slug(name)
    batch_prefix = ctx.get("batch_prefix") or f"{slug}-issue"

    # Extract base_url + ojs_prefix from the archive URL
    archive_url = ctx.get("archive_url", "").rstrip("/")
    parsed = urlparse(archive_url) if archive_url else None
    base_url = f"{parsed.scheme}://{parsed.netloc}" if parsed and parsed.scheme else "https://example.org"
    m = _OJS_PATH.search(archive_url) if archive_url else None
    ojs_prefix = f"/index.php/{m.group(1)}" if m else f"/index.php/{slug}"

    # DOI pattern guess — user should refine after first run
    doi_pattern = ctx.get("doi_pattern", "10\\.[0-9]+/[A-Za-z0-9._-]+")

    journal_dir.mkdir(parents=True, exist_ok=True)
    (journal_dir / "journal.py").write_text(
        _JOURNAL_PY.format(
            name=name, slug=slug, batch_prefix=batch_prefix,
            base_url=base_url, ojs_prefix=ojs_prefix,
            doi_pattern=doi_pattern,
        ),
        encoding="utf-8",
    )
    (journal_dir / "downloader.py").write_text(
        _DOWNLOADER_PY.format(name=name, slug=slug),
        encoding="utf-8",
    )
    (journal_dir / "scraper.py").write_text(
        _SCRAPER_PY.format(name=name),
        encoding="utf-8",
    )

    import json
    (journal_dir / "depositor.json").write_text(
        json.dumps({
            "depositor_name": ctx.get("depositor_name", ""),
            "email_address": ctx.get("depositor_email", ""),
        }, indent=2),
        encoding="utf-8",
    )

    # Copy Prompt's enricher.py as the starter (closest sibling OJS journal)
    src = journal_dir.parent / "Prompt" / "Structured Scraper" / "enricher.py"
    dest_dir = journal_dir / "Structured Scraper"
    dest_dir.mkdir(parents=True, exist_ok=True)
    if src.exists():
        (dest_dir / "enricher.py").write_bytes(src.read_bytes())
        req = src.parent / "requirements.txt"
        if req.exists():
            (dest_dir / "requirements.txt").write_bytes(req.read_bytes())
    else:
        # Fall back to ATD's enricher
        atd_src = journal_dir.parent / "Across the Disciplines" / "Structured Scraper" / "enricher.py"
        if atd_src.exists():
            (dest_dir / "enricher.py").write_bytes(atd_src.read_bytes())


PLATFORM = Platform(
    key="ojs",
    label="Open Journal Systems (OJS)",
    detect=_detect,
    default_slug=_default_slug,
    scaffold=_scaffold,
    notes=[
        "OJS articles often have both HTML and PDF galleys; the downloader "
        "saves both, the scraper prefers HTML when present.",
        "Confirm the DOI pattern in journal.py matches your journal's actual "
        "DOI stem before running the first extraction.",
        "Depositor credentials are saved to <Journal>/depositor.json which is "
        "gitignored.",
    ],
)
