"""Fallback platform when URL detection doesn't recognize the host.

Generates a journal.py + a stub downloader.py with TODO comments. The
user fills in the downloader by hand for unusual hosting arrangements
(OAI-PMH harvest, custom CMS, etc.).
"""
from __future__ import annotations

from pathlib import Path

from .base import Platform, _basic_slug


def _detect(url: str, html: str) -> bool:
    # Always returns False — this is the final fallback chosen by the
    # caller, never auto-detected.
    return False


def _default_slug(url: str) -> tuple[str, str, str]:
    return ("New Journal", "newjournal", "newjournal-volume")


_JOURNAL_PY = '''"""
Journal-specific config for {name}.

Generated by the New Journal wizard. The hosting platform was not
auto-detected, so you'll need to fill in downloader.py by hand.
"""

from __future__ import annotations


JOURNAL_NAME = "{name}"
JOURNAL_SLUG = "{slug}"
BATCH_ID_PREFIX = "{batch_prefix}"


EXTRACTION_CONFIG = {{
    "use_doi_annotation_extraction": True,
    "use_low_text_ocr":              True,
    "use_scramble_detection":        True,
    "use_page_break_recovery":       True,
    "use_mla_tei_fallback":          True,
    "use_mla_raw_text_fallback":     True,
    "use_anystyle_fallback":         True,
    "use_per_citation_parse":        True,
    "use_em_dash_patcher":           True,
    "force_ocr_volumes":             [],
    "min_text_chars_for_skip_ocr":   3000,
    "scramble_ratio_threshold":      1.5,
    "anystyle_container":            "anystyle",
    "anystyle_http_url":             "http://localhost:4567",
}}


ENRICHMENT_CONFIG = {{
    "crossref":         True,
    "openalex":         False,
    "semantic_scholar": False,
    "rate_limit_s":     0.1,
}}
'''


_DOWNLOADER_STUB = '''"""
{name} downloader — STUB.

The New Journal wizard didn't recognize the hosting platform, so this
file is a placeholder. Fill in the discovery + download logic for
your journal's archive site.

Convention: PDFs go to ./pdfs/<vol_slug>/<basename>.pdf where <vol_slug>
is `volume<N>` for simple volume archives or `v<N>i<M>` for issue-based
archives.
"""

import sys


def main():
    print("downloader.py is a stub — fill in the discovery logic for "
          "{name}'s archive.", file=sys.stderr)
    sys.exit(1)


if __name__ == "__main__":
    main()
'''


_SCRAPER_PY = '''"""
{name} reference scraper.

Thin wrapper around `_shared.cli.run`.
"""

from __future__ import annotations

import sys
from pathlib import Path


_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
for _p in (str(_PROJECT_ROOT), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from _shared.cli import run  # noqa: E402
import journal  # noqa: E402


if __name__ == "__main__":
    sys.exit(run(journal))
'''


def _scaffold(journal_dir: Path, ctx: dict) -> None:
    name = ctx["name"]
    slug = ctx.get("slug") or _basic_slug(name)
    batch_prefix = ctx.get("batch_prefix") or f"{slug}-volume"

    journal_dir.mkdir(parents=True, exist_ok=True)
    (journal_dir / "journal.py").write_text(
        _JOURNAL_PY.format(name=name, slug=slug, batch_prefix=batch_prefix),
        encoding="utf-8",
    )
    (journal_dir / "downloader.py").write_text(
        _DOWNLOADER_STUB.format(name=name),
        encoding="utf-8",
    )
    (journal_dir / "scraper.py").write_text(
        _SCRAPER_PY.format(name=name),
        encoding="utf-8",
    )
    import json
    (journal_dir / "depositor.json").write_text(
        json.dumps({
            "depositor_name": ctx.get("depositor_name", ""),
            "email_address": ctx.get("depositor_email", ""),
        }, indent=2),
        encoding="utf-8",
    )


PLATFORM = Platform(
    key="unknown",
    label="Other (manual setup)",
    detect=_detect,
    default_slug=_default_slug,
    scaffold=_scaffold,
    notes=[
        "Your archive's hosting wasn't auto-detected. The wizard will "
        "generate journal.py + a stub downloader.py — you'll need to fill "
        "in the downloader logic by hand before running Stage 1.",
        "Look at the existing journals' downloader.py files (especially "
        "Reflections for OAI-PMH harvests) as starting points.",
    ],
)
