"""WAC Clearinghouse platform (wac.colostate.edu / wacclearinghouse.org).

Hosts: ATD, The WAC Journal, JBW, Double Helix, JWA, and many others
in writing studies. Volume URLs follow:
    https://wac.colostate.edu/docs/<slug>/vol<N>/<author>.pdf
    https://wacclearinghouse.org/<slug>/archives/volume<N>/

The downloader walks the volume index page (HTML), pulls every <a href>
ending in `.pdf` whose URL contains `/docs/<slug>/vol<N>/`, and downloads
each into `pdfs/volume<N>/`.
"""
from __future__ import annotations

import re
from pathlib import Path
from urllib.parse import urlparse

from .base import Platform, _basic_slug


def _detect(url: str, html: str) -> bool:
    host = urlparse(url).netloc.lower()
    if "wac.colostate.edu" in host:
        return True
    if "wacclearinghouse.org" in host:
        return True
    # Fallback: HTML body contains a WAC Clearinghouse footer
    if "WAC Clearinghouse" in (html or ""):
        return True
    return False


_SLUG_FROM_URL = re.compile(
    r"(?:wacclearinghouse\.org|wac\.colostate\.edu)/(?:docs/)?([a-z0-9_-]+)/",
    re.IGNORECASE,
)


def _default_slug(url: str) -> tuple[str, str, str]:
    """Guess (name, slug, batch_prefix). Best-effort from URL path."""
    m = _SLUG_FROM_URL.search(url)
    if m:
        slug = m.group(1).lower()
        # Title-case the slug as a name guess
        name_guess = slug.replace("-", " ").replace("_", " ").upper()
        return (name_guess, slug, f"{slug}-volume")
    return ("New Journal", "newjournal", "newjournal-volume")


_JOURNAL_PY = '''"""
Journal-specific config for {name}.

Generated by the New Journal wizard for a WAC Clearinghouse-hosted journal.
Re-tune `force_ocr_volumes` after running the sampler.
"""

from __future__ import annotations


JOURNAL_NAME = "{name}"
JOURNAL_SLUG = "{slug}"
BATCH_ID_PREFIX = "{batch_prefix}"


EXTRACTION_CONFIG = {{
    "use_doi_annotation_extraction": True,
    "use_low_text_ocr":              True,
    "use_scramble_detection":        True,
    "use_page_break_recovery":       True,
    "use_mla_tei_fallback":          True,
    "use_mla_raw_text_fallback":     True,
    "use_anystyle_fallback":         True,
    "use_per_citation_parse":        True,
    "use_em_dash_patcher":           True,
    "force_ocr_volumes":             {force_ocr_volumes},
    "min_text_chars_for_skip_ocr":   3000,
    "scramble_ratio_threshold":      1.5,
    "anystyle_container":            "anystyle",
    "anystyle_http_url":             "http://localhost:4567",
}}


ENRICHMENT_CONFIG = {{
    "crossref":         True,
    "openalex":         False,
    "semantic_scholar": False,
    "rate_limit_s":     0.1,
}}
'''


_DOWNLOADER_PY = '''"""
{name} volume downloader.

Walks a WAC Clearinghouse volume index page, finds every article PDF link,
and downloads each into a per-volume folder. Idempotent — already-downloaded
PDFs are skipped.

Usage:
    python downloader.py 21                  # one volume into pdfs/volume21/
    python downloader.py 20 21 22            # multiple
"""

from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup


BASE_URL = "{base_url}"
VOLUME_URL_TEMPLATE = "{volume_url_template}"
USER_AGENT = "{slug}-reference-scraper/1.0 (+local research tool)"
DOWNLOAD_DELAY_S = 0.5


def list_pdfs(volume_url: str, session: requests.Session) -> list[str]:
    r = session.get(volume_url, timeout=30)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    out: list[str] = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if href.lower().endswith(".pdf"):
            out.append(urljoin(volume_url, href))
    return sorted(set(out))


def download_volume(vol: int, out_root: Path, session: requests.Session) -> int:
    vol_url = VOLUME_URL_TEMPLATE.format(n=vol)
    vol_dir = out_root / f"volume{{vol}}"
    vol_dir.mkdir(parents=True, exist_ok=True)
    pdfs = list_pdfs(vol_url, session)
    print(f"[vol{{vol}}] {{len(pdfs)}} PDFs at {{vol_url}}", flush=True)
    written = 0
    for url in pdfs:
        name = urlparse(url).path.rsplit("/", 1)[-1]
        target = vol_dir / name
        if target.exists() and target.stat().st_size > 0:
            continue
        try:
            r = session.get(url, timeout=120, stream=True)
            r.raise_for_status()
            target.write_bytes(r.content)
            written += 1
            print(f"  ↓ {{name}} ({{target.stat().st_size//1024}} KB)", flush=True)
            time.sleep(DOWNLOAD_DELAY_S)
        except Exception as e:
            print(f"  !! {{name}}: {{e}}", flush=True)
    return written


def main():
    p = argparse.ArgumentParser()
    p.add_argument("volumes", nargs="+", type=int)
    p.add_argument("--output", default="pdfs")
    args = p.parse_args()
    out_root = Path(args.output).resolve()

    session = requests.Session()
    session.headers["User-Agent"] = USER_AGENT
    total = 0
    for v in args.volumes:
        total += download_volume(v, out_root, session)
    print(f"=== done: {{total}} new PDFs downloaded", flush=True)


if __name__ == "__main__":
    main()
'''


_SCRAPER_PY = '''"""
{name} reference scraper.

Thin wrapper around `_shared.cli.run`. Per-journal config lives in journal.py.
"""

from __future__ import annotations

import sys
from pathlib import Path


_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
for _p in (str(_PROJECT_ROOT), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from _shared.cli import run  # noqa: E402
import journal  # noqa: E402


if __name__ == "__main__":
    sys.exit(run(journal))
'''


def _scaffold(journal_dir: Path, ctx: dict) -> None:
    """Write the per-journal scaffolding files into `journal_dir`.

    ctx keys consumed:
      name, slug, batch_prefix, base_url, archive_url,
      force_ocr_volumes (list[int]),
      depositor_name, depositor_email
    """
    name = ctx["name"]
    slug = ctx.get("slug") or _basic_slug(name)
    batch_prefix = ctx.get("batch_prefix") or f"{slug}-volume"
    base_url = ctx.get("base_url") or "https://wacclearinghouse.org"
    # WAC Clearinghouse volume URL conventions vary; user can edit later.
    archive_url = ctx.get("archive_url", "").rstrip("/")
    if "{n}" in archive_url:
        volume_url_template = archive_url
    elif "/volume" in archive_url.lower():
        volume_url_template = re.sub(r"/volume\d+/?$", "/volume{n}/", archive_url) + "/"
        volume_url_template = volume_url_template.rstrip("/") + "/"
    else:
        volume_url_template = f"{base_url}/{slug}/archives/volume{{n}}/"

    force_ocr_volumes = ctx.get("force_ocr_volumes") or []

    journal_dir.mkdir(parents=True, exist_ok=True)
    (journal_dir / "journal.py").write_text(
        _JOURNAL_PY.format(
            name=name, slug=slug, batch_prefix=batch_prefix,
            force_ocr_volumes=repr(list(force_ocr_volumes)),
        ),
        encoding="utf-8",
    )
    (journal_dir / "downloader.py").write_text(
        _DOWNLOADER_PY.format(
            name=name, slug=slug,
            base_url=base_url,
            volume_url_template=volume_url_template,
        ),
        encoding="utf-8",
    )
    (journal_dir / "scraper.py").write_text(
        _SCRAPER_PY.format(name=name),
        encoding="utf-8",
    )

    # depositor.json (gitignored — credentials)
    import json
    (journal_dir / "depositor.json").write_text(
        json.dumps({
            "depositor_name": ctx.get("depositor_name", ""),
            "email_address": ctx.get("depositor_email", ""),
        }, indent=2),
        encoding="utf-8",
    )

    # Stub the Structured Scraper enricher dir; copy the closest existing
    # enricher.py from a sibling WAC journal as the starter, since the
    # enrichers are nearly identical across journals.
    _stub_enricher(journal_dir)


def _stub_enricher(journal_dir: Path) -> None:
    """Copy an existing WAC journal's enricher.py as the starter."""
    src = journal_dir.parent / "Across the Disciplines" / "Structured Scraper" / "enricher.py"
    dest_dir = journal_dir / "Structured Scraper"
    dest_dir.mkdir(parents=True, exist_ok=True)
    if src.exists():
        (dest_dir / "enricher.py").write_bytes(src.read_bytes())
        req = src.parent / "requirements.txt"
        if req.exists():
            (dest_dir / "requirements.txt").write_bytes(req.read_bytes())
    else:
        (dest_dir / "enricher.py").write_text(
            "# TODO: copy enricher.py from a sibling journal\n",
            encoding="utf-8",
        )


PLATFORM = Platform(
    key="wac",
    label="WAC Clearinghouse",
    detect=_detect,
    default_slug=_default_slug,
    scaffold=_scaffold,
    notes=[
        "Volume URLs follow /<slug>/archives/volume<N>/ — the wizard will "
        "guess the template from the URL you provide.",
        "Early volumes are often scanned PDFs without a text layer; the sampler "
        "step (Stage 0/2) is the best way to figure out which to force-OCR.",
        "Depositor credentials are saved to <Journal>/depositor.json which is "
        "gitignored.",
    ],
)
